CREATE USER jambeth_testutil_user IDENTIFIED BY jambeth;

GRANT CONNECT,CREATE SESSION,RESOURCE TO jambeth_testutil_user;

CREATE TABLE jambeth_testutil_user.PROJECT
  (
    "ID"   NUMBER(18,0) NOT NULL,
    "ALTERNATE_KEY"   NUMBER(18,0) NOT NULL,
    "NAME" VARCHAR2(50 BYTE) NOT NULL,
    "DESCRIPTION" VARCHAR2(1000 BYTE),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    "VERSION"    NUMBER(18,0),
    CONSTRAINT "PROJECT_PK" PRIMARY KEY ("ID") USING INDEX
  );

CREATE SEQUENCE jambeth_testutil_user.PROJECT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

GRANT ALL ON jambeth_testutil_user.PROJECT TO jambeth;
