INSERT INTO "PROJECT" (ID, ALTERNATE_KEY, NAME, VERSION) VALUES (11, 11, 'Base Project 11', 1);
INSERT INTO "PROJECT" (ID, ALTERNATE_KEY, NAME, VERSION) VALUES (12, 12, 'Base Project 12', 1);
INSERT INTO "PROJECT" (ID, ALTERNATE_KEY, NAME, VERSION) VALUES (13, 13, 'Base Project 13', 1);
