---
-- #%L
-- jambeth-test
-- %%
-- Copyright (C) 2017 Koch Softwaredevelopment
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-- #L%
---

CREATE TABLE "ENTITY_A" (
	"ID"			NUMBER(9,0) NOT NULL,
	"NAME"			VARCHAR2(16 BYTE) NOT NULL,
	"ENTITY_B_ID"	NUMBER(9,0),
	"CREATED_ON"	DATE,
	"CREATED_BY"	VARCHAR2(16 BYTE),
	"UPDATED_ON"	DATE,
	"UPDATED_BY"	VARCHAR2(16 BYTE),
	"VERSION"		NUMBER(9,0),
	CONSTRAINT "ENTITY_A_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "ENTITY_A_AK_NAME" UNIQUE ("NAME") USING INDEX
);
CREATE SEQUENCE "ENTITY_A_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ENTITY_B" (
	"ID"			NUMBER(9,0) NOT NULL,
	"NAME"			VARCHAR2(16 BYTE) NOT NULL,
	"CREATED_ON"	DATE,
	"CREATED_BY"	VARCHAR2(16 BYTE),
	"UPDATED_ON"	DATE,
	"UPDATED_BY"	VARCHAR2(16 BYTE),
	"VERSION"		NUMBER(9,0),
	CONSTRAINT "ENTITY_B_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "ENTITY_B_AK_NAME" UNIQUE ("NAME") USING INDEX
);
CREATE SEQUENCE "ENTITY_B_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "LINK_ENTITY_A_ENTITY_B" (
	"LEFT_ID"  NUMBER(9,0) NOT NULL,
	"RIGHT_ID" NUMBER(9,0) NOT NULL,
	CONSTRAINT "LINK_MATERIAL_UNIT_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
	CONSTRAINT "LINK_ENT_A_ENT_B_ENT_A_FK1" FOREIGN KEY ("LEFT_ID") REFERENCES "ENTITY_A" ("ID") DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT "LINK_ENT_A_ENT_B_ENT_B_FK1" FOREIGN KEY ("RIGHT_ID") REFERENCES "ENTITY_B" ("ID") DEFERRABLE INITIALLY DEFERRED
);
