INSERT INTO "ENTITY_A" ("ID","VERSION") VALUES (1, 1);
INSERT INTO "ENTITY_A" ("ID","VERSION") VALUES (2, 1);
INSERT INTO "ENTITY_B" ("ID","VERSION", "ENTITY_A") VALUES (11, 1, 1);
INSERT INTO "ENTITY_B" ("ID","VERSION", "ENTITY_A") VALUES (12, 1, 2);
INSERT INTO "ENTITY_C" ("ID","VERSION", "ENTITY_A") VALUES (111, 1, 1);
INSERT INTO "ENTITY_C" ("ID","VERSION", "ENTITY_A") VALUES (112, 1, 1);
INSERT INTO "ENTITY_C" ("ID","VERSION", "ENTITY_A") VALUES (121, 1, 2);
INSERT INTO "ENTITY_C" ("ID","VERSION", "ENTITY_A") VALUES (122, 1, 2);