INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'A_10000_Name'||"QUERY_ENTITY_SEQ".NEXTVAL, '2');
INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'Q10000NameA'||"QUERY_ENTITY_SEQ".NEXTVAL, '2');
INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'Q_10000NameA'||"QUERY_ENTITY_SEQ".NEXTVAL, '2');
INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'Q_10000_Nam'||"QUERY_ENTITY_SEQ".NEXTVAL, '2');

--: loop = 5000
INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'Q_10000_Name'||"QUERY_ENTITY_SEQ".NEXTVAL, '2');

--: loop = 5000
INSERT INTO "QUERY_ENTITY" ("ID", "NAME1", "VERSION") VALUES ("QUERY_ENTITY_SEQ".NEXTVAL, 'Q_10000_Name'||"QUERY_ENTITY_SEQ".NEXTVAL, '3');
