package com.koch.ambeth.security;

public interface IAuthorizationChangeListenerExtendable
{
	void registerAuthorizationChangeListener(IAuthorizationChangeListener authorizationChangeListener);

	void unregisterAuthorizationChangeListener(IAuthorizationChangeListener authorizationChangeListener);
}