INSERT INTO PARENT (ID, VERSION) SELECT PARENT_SEQ.NEXTVAL, '1' FROM DUAL CONNECT BY LEVEL <= 3000;

INSERT INTO CHILD (ID, PARENT, VERSION) SELECT CHILD_SEQ.NEXTVAL, ID, '1' FROM PARENT CONNECT BY LEVEL <= 2;
