INSERT INTO "ENTITY_A" (ID, NAME, ENTITY_B_ID, VERSION) VALUES ('1', 'ENTITY_A 1', '11', '1');
INSERT INTO "ENTITY_A" (ID, NAME, ENTITY_B_ID, VERSION) VALUES ('2', 'ENTITY_A 2', '11', '1');

INSERT INTO "ENTITY_B" (ID, NAME, VERSION) VALUES ('11', 'ENTITY_B 11', '1');
INSERT INTO "ENTITY_B" (ID, NAME, VERSION) VALUES ('12', 'ENTITY_B 12', '1');