CREATE TABLE "ADDRESS_PG" (
	"USER_ID" VARCHAR2(64 CHAR) NOT NULL,
	"PERM_GROUP_ID" NUMBER(18,0) NOT NULL,
	"READ" NUMBER(1,0),
	CONSTRAINT "ADDRESS_PG_PK" PRIMARY KEY ("USER_ID","PERM_GROUP_ID") USING INDEX );
CREATE INDEX "ADDRESS_PG_IDX" ON "ADDRESS_PG" ("PERM_GROUP_ID");
ALTER TABLE "ADDRESS" ADD "PERM_GROUP" NUMBER(18,0);

CREATE TABLE "BOAT_PG" (
	"USER_ID" VARCHAR2(64 CHAR) NOT NULL,
	"PERM_GROUP_ID" NUMBER(18,0) NOT NULL,
	"READ" NUMBER(1,0),
	CONSTRAINT "BOAT_PG_PK" PRIMARY KEY ("USER_ID","PERM_GROUP_ID") USING INDEX );
CREATE INDEX "BOAT_PG_IDX" ON "BOAT_PG" ("PERM_GROUP_ID");
ALTER TABLE "BOAT" ADD "PERM_GROUP" NUMBER(18,0);

CREATE TABLE "EMPLOYEE_PG" (
	"USER_ID" VARCHAR2(64 CHAR) NOT NULL,
	"PERM_GROUP_ID" NUMBER(18,0) NOT NULL,
	"READ" NUMBER(1,0),
	CONSTRAINT "EMPLOYEE_PG_PK" PRIMARY KEY ("USER_ID","PERM_GROUP_ID") USING INDEX );
CREATE INDEX "EMPLOYEE_PG_IDX" ON "EMPLOYEE_PG" ("PERM_GROUP_ID");
ALTER TABLE "EMPLOYEE" ADD "PERM_GROUP" NUMBER(18,0);

CREATE TABLE "PROJECT_PG" (
	"USER_ID" VARCHAR2(64 CHAR) NOT NULL,
	"PERM_GROUP_ID" NUMBER(18,0) NOT NULL,
	"READ" NUMBER(1,0),
	CONSTRAINT "PROJECT_PG_PK" PRIMARY KEY ("USER_ID","PERM_GROUP_ID") USING INDEX );
CREATE INDEX "PROJECT_PG_IDX" ON "PROJECT_PG" ("PERM_GROUP_ID");
ALTER TABLE "PROJECT" ADD "PERM_GROUP" NUMBER(18,0);

ALTER TABLE "LINK_EMPLOYEE_PROJECT" ADD "TO_EMPLOYEE_ID_PG" NUMBER(18,0);
ALTER TABLE "LINK_EMPLOYEE_PROJECT" ADD "TO_PROJECT_ID_PG" NUMBER(18,0);

