INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, FK, VERSION) VALUES ('1', 'name1_name2', 'name3', 'name1_name2', 1.0, '2', '2');
INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, VERSION) VALUES ('2', 'name1', 'name2', 'name1', 2.1, '1');
INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, FK, VERSION) VALUES ('3', 'name1', 'name3', 'name1', 3.2, '1', '2');
INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, FK, VERSION) VALUES ('4', 'name3', 'name1', 'name3', 4.3, '2', '1');
INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, VERSION) VALUES ('5', 'name1', 'name1', 'name1', 5.4, '2');
INSERT INTO "QUERY_ENTITY" (ID, NAME1, NAME2, FTNAME1, CONTENT, FK, VERSION) VALUES ('6', 'name1', 'name1', 'name1', 5.4, '1', '2');

INSERT INTO "JOIN_QUERY_ENTITY" (ID, PARENT, CONTENT, VERSION) VALUES ('1', '2', 3.14, '2');
INSERT INTO "JOIN_QUERY_ENTITY" (ID, CONTENT, VERSION) VALUES ('2', 2.7, '3');
INSERT INTO "JOIN_QUERY_ENTITY" (ID, CONTENT, VERSION) VALUES ('3', 0.125, '1');

CALL CTX_DDL.SYNC_INDEX('FTI_QE_FTNAME1', '2M');