CREATE TABLE "ENTITY_A"
  (
    "ID"   			NUMBER(9,0) NOT NULL,
    "BUID"			VARCHAR2(20 CHAR) NOT NULL,
    "ENTITY_B"		NUMBER,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 CHAR),
    "CREATED_BY"	VARCHAR2(16 CHAR),
    "VERSION"   	NUMBER(9,0),
    CONSTRAINT "PK_ENTITY_A" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "UK_ENTITY_A_BUID" UNIQUE ("BUID"),
    CONSTRAINT "LINK_ENTITY_A_ENTITY_B_FK1" FOREIGN KEY ("ENTITY_B") REFERENCES "ENTITY_B" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "ENTITY_A_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "ENTITY_B"
  (
    "ID"			NUMBER NOT NULL,
    "BUID"			VARCHAR2(20 CHAR) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 CHAR),
    "CREATED_BY"	VARCHAR2(16 CHAR),
    "VERSION"   	NUMBER(*,0),
    CONSTRAINT "UK_ENTITY_B_BUID" UNIQUE ("BUID"),
    CONSTRAINT "PK_ENTITY_B" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "ENTITY_B_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;
