CREATE TABLE NO_VERSION_BACKING
(
	"ID"		NUMBER NOT NULL,
	"NAME"		VARCHAR2(50 CHAR) NOT NULL,
	CONSTRAINT "NO_VERSION_BACKING_PK" PRIMARY KEY ("ID") USING INDEX
);
/

CREATE SEQUENCE NO_VERSION_BACKING_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE VIEW NO_VERSION ("ID", "NAME") AS SELECT "ID", "NAME" FROM NO_VERSION_BACKING;
