CREATE TABLE "HOME_ADDRESS"
  (
    "ID" 						NUMBER(9,0) NOT NULL,
    "VERSION"					NUMBER(9,0) NOT NULL,
    "STREAT"			        VARCHAR2(400 CHAR) NOT NULL,
    CONSTRAINT "HOME_ADDRESS_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "HOME_ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ADDRESS"
  (
    "ID" 						NUMBER(9,0) NOT NULL,
    "VERSION"					NUMBER(9,0) NOT NULL,
    "NAME"			            VARCHAR2(400 CHAR) NOT NULL,
    CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "HOME"
  (
    "ID" 						NUMBER(9,0) NOT NULL,
    "VERSION"					NUMBER(9,0) NOT NULL,
    "ADDRESS_ID"			    NUMBER(9,0),
    CONSTRAINT "HOME_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "L_HOME_FK_ADDRESS" FOREIGN KEY ("ADDRESS_ID") REFERENCES "ADDRESS" ("ID") DEFERRABLE INITIALLY DEFERRED 
  );
CREATE SEQUENCE "HOME_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER NOCYCLE ;
CREATE INDEX "L_HOME_FK_ADDRESS" ON "HOME" ("ADDRESS_ID");


CREATE TABLE "PERSON"
  (
    "ID"			        NUMBER(9,0) NOT NULL,
    "VERSION"		        NUMBER(9,0),
    "NAME"	                VARCHAR2(20 CHAR),
    "AGE"		            NUMBER(9,0),
    "HAVE_ANDRIOD"			NUMBER(1,0),
    "HAVE_ORANGE"			NUMBER(1,0),
	"MODIFY_TIME" 			TIMESTAMP,
	"HOME_ID"			    NUMBER(9,0),
	"HOME_ADDRESS_ID"		NUMBER(9,0),
    CONSTRAINT "PK_MAID_ENTITY" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "L_PERSON_FK_HOME" FOREIGN KEY ("HOME_ID") REFERENCES "HOME" ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "L_PERSON_FK_HOME_ADDRESS" FOREIGN KEY ("HOME_ADDRESS_ID") REFERENCES "HOME_ADDRESS" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "PERSON_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;
CREATE INDEX "L_PERSON_FK_HOME" ON "PERSON" ("HOME_ID");
CREATE INDEX "L_PERSON_FK_HOME_ADDRESS" ON "PERSON" ("HOME_ADDRESS_ID");
