CREATE TABLE "ENTITY"
(
	"ID"		NUMBER NOT NULL,
    "NAME"		VARCHAR2(20 CHAR),
    "NAME1"		VARCHAR2(20 CHAR),
	"VERSION"	NUMBER(*,0),
	CONSTRAINT "PK_QUERY_ENTITY" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "QUERY_ENTITY_SEQ" MINVALUE 1 MAXVALUE 2000000000 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;
