CREATE TABLE "PASSWORD"
  (
	"ID" 				NUMBER(9,0) NOT NULL,
	"UPDATED_ON"		TIMESTAMP,
	"CREATED_ON"		TIMESTAMP,
	"UPDATED_BY"		VARCHAR2(64 CHAR),
	"CREATED_BY"		VARCHAR2(64 CHAR),
	"VERSION"			NUMBER(9,0) NOT NULL,
	"CHANGE_AFTER"		TIMESTAMP NOT NULL,
	"USER_ID"			NUMBER(9,0),
	"VALUE"				VARCHAR2(64 CHAR) NOT NULL,
	"SALT"				VARCHAR2(64 CHAR) NOT NULL,
	"ALGORITHM"			VARCHAR2(64 CHAR) NOT NULL,
	"ITERATION_COUNT"	NUMBER(9,0) NOT NULL,
	"KEYSIZE"			NUMBER(9,0) NOT NULL,
	"SALT_LENGTH"		NUMBER(9,0),
	"SALT_ENCRYPTION_ALGORITHM"		VARCHAR2(64 CHAR),
	"SALT_ENCRYPTION_KEY_SPEC"		VARCHAR2(64 CHAR),
	"SALT_ENCRYPTION_KEY_IV"		VARCHAR2(173 CHAR),
	"SALT_PADDED_KEY_ALGORITHM"		VARCHAR2(64 CHAR),
	"SALT_PADDED_KEY_SIZE"			NUMBER(9,0),
	"SALT_PADDED_KEY_ITERATIONS"	NUMBER(9,0),
    CONSTRAINT "PASSWORD_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "PASSWORD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "USER"
  (
	"ID" 			NUMBER(9,0) NOT NULL,
	"UPDATED_ON"	TIMESTAMP,
	"CREATED_ON"	TIMESTAMP,
	"UPDATED_BY"	VARCHAR2(64 CHAR),
	"CREATED_BY"	VARCHAR2(64 CHAR),
	"VERSION"		NUMBER(9,0) NOT NULL,
	"SID"			VARCHAR2(50 CHAR) NOT NULL,
	"NAME"			VARCHAR2(50 CHAR),
	"SURNAME"		VARCHAR2(50 CHAR),
	"DISPLAYNAME"	VARCHAR2(50 CHAR),
	"PASSWORD_ID"	NUMBER(9,0) NOT NULL,
	"ACTIVE"		NUMBER(1,0) NOT NULL,
	CONSTRAINT "USER_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "USER_UQ_PASSWORD_ID" UNIQUE ("PASSWORD_ID"),
	CONSTRAINT "USER_UQ_SID" UNIQUE ("SID"),
	CONSTRAINT "USER_FK_PASSWORD_ID" FOREIGN KEY ("PASSWORD_ID") REFERENCES "PASSWORD" ("ID") DEFERRABLE INITIALLY DEFERRED
  );
CREATE SEQUENCE "USER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

ALTER TABLE "PASSWORD" ADD CONSTRAINT "PASSWORD_FK_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "PASSWORD_FK_USER_ID_IDX" ON "PASSWORD" ("USER_ID");

CREATE TABLE "SIGNATURE" 
(	
	"ID"					NUMBER(9,0) NOT NULL,
	"CREATED_ON"			TIMESTAMP,
	"UPDATED_ON"			TIMESTAMP,
	"UPDATED_BY"			VARCHAR2(64 CHAR),
	"CREATED_BY"			VARCHAR2(64 CHAR),
	"VERSION"				NUMBER(9,0) NOT NULL,
	"USER_ID"				NUMBER(9,0),
	"SIGNATURE_ALGORITHM"	VARCHAR2(64 CHAR) NOT NULL,
	"KEY_FACTORY_ALGORITHM"	VARCHAR2(64 CHAR) NOT NULL,
	"ENCRYPTION_ALGORITHM"	VARCHAR2(64 CHAR) NOT NULL,
	"ENCRYPTION_KEY_SPEC"	VARCHAR2(64 CHAR) NOT NULL,
	"ENCRYPTION_KEY_IV"		VARCHAR2(173 CHAR) NOT NULL,
	"PADDED_KEY_ALGORITHM"	VARCHAR2(64 CHAR) NOT NULL,
	"PADDED_KEY_SIZE"		NUMBER(9,0) NOT NULL,
	"PADDED_KEY_ITERATIONS"	NUMBER(9,0) NOT NULL,
	"PADDED_KEY_SALT_SIZE"	NUMBER(9,0) NOT NULL,
	"PADDED_KEY_SALT"		VARCHAR2(64 CHAR) NOT NULL,
	"PRIVATE_KEY"			VARCHAR2(700 CHAR) NOT NULL,
	"PUBLIC_KEY"			VARCHAR2(700 CHAR) NOT NULL,
	CONSTRAINT "SIGNATURE_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "SIGNATURE_FK_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "SIGNATURE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
CREATE INDEX "SIGNATURE_FK_USER_ID_IDX" ON "SIGNATURE" ("USER_ID");
