CREATE OR REPLACE TYPE "LONG_ARRAY" AS VARRAY(4000) OF NUMBER(19,0);

CREATE OR REPLACE TYPE "INT_ARRAY" AS VARRAY(4000) OF NUMBER(10,0);

CREATE OR REPLACE TYPE "SHORT_ARRAY" AS VARRAY(4000) OF NUMBER(5,0);

CREATE OR REPLACE TYPE "BYTE_ARRAY" AS VARRAY(4000) OF NUMBER(3,0);

CREATE OR REPLACE TYPE "CHAR_ARRAY" AS VARRAY(4000) OF NCHAR;

CREATE OR REPLACE TYPE "BOOL_ARRAY" AS VARRAY(4000) OF NUMBER(1,0);

CREATE OR REPLACE TYPE "DOUBLE_ARRAY" AS VARRAY(4000) OF NUMBER(20,10);

CREATE OR REPLACE TYPE "FLOAT_ARRAY" AS VARRAY(4000) OF NUMBER(10,5);

CREATE OR REPLACE TYPE "STRING_ARRAY" AS VARRAY(4000) OF VARCHAR2(4000 CHAR);

CREATE TABLE "ARRAY_OBJECT"
  (
    "ID"   NUMBER NOT NULL,
    "LONG_CONTENT" LONG_ARRAY,
    "LONG_CONTENT2" LONG_ARRAY,
    "SET_LONG_CONTENT" LONG_ARRAY,
    "LIST_LONG_CONTENT" LONG_ARRAY,
    "COLL_LONG_CONTENT" LONG_ARRAY,
    "INT_CONTENT" INT_ARRAY,
    "INT_CONTENT2" INT_ARRAY,
    "SHORT_CONTENT" SHORT_ARRAY,
    "SHORT_CONTENT2" SHORT_ARRAY,
    "BYTE_CONTENT" BYTE_ARRAY,
    "BYTE_CONTENT2" BYTE_ARRAY,
    "CHAR_CONTENT" CHAR_ARRAY,
    "CHAR_CONTENT2" CHAR_ARRAY,
    "BOOL_CONTENT" BOOL_ARRAY,
    "BOOL_CONTENT2" BOOL_ARRAY,
    "DOUBLE_CONTENT" DOUBLE_ARRAY,
    "DOUBLE_CONTENT2" DOUBLE_ARRAY,
    "FLOAT_CONTENT" FLOAT_ARRAY,
    "FLOAT_CONTENT2" FLOAT_ARRAY,
    "STRING_CONTENT" STRING_ARRAY,
    "LIST_STRING_CONTENT" STRING_ARRAY,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "ARRAY_OBJECT_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ARRAY_OBJECT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
