CREATE TABLE CHILD
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
  );

CREATE TABLE PARENT
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    "CHILD"		NUMBER NULL,
    CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "PARENT_CHILD_FK" FOREIGN KEY ("CHILD") REFERENCES CHILD ("ID") DEFERRABLE INITIALLY IMMEDIATE
 );
