---
-- #%L
-- jambeth-test
-- %%
-- Copyright (C) 2017 Koch Softwaredevelopment
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-- #L%
---

CREATE TABLE CI_ADMIN.CHILD
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE CI_ADMIN.CHILD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE CI_ADMIN.PARENT
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    "CHILD"		NUMBER NULL,
    CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "PARENT_CHILD_FK" FOREIGN KEY ("CHILD") REFERENCES CI_ADMIN.CHILD ("ID") DEFERRABLE INITIALLY IMMEDIATE
  );
CREATE SEQUENCE CI_ADMIN.PARENT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

--CREATE TABLE CI_ADMIN_B.CHILD
--  (
--    "ID"		NUMBER NOT NULL,
--    "VERSION"	NUMBER(*,0),
--    CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
--  );
--CREATE SEQUENCE CI_ADMIN_B.CHILD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
--
-- CREATE TABLE CI_ADMIN_B.PARENT
--   (
--     "ID"		NUMBER NOT NULL,
--     "VERSION"	NUMBER(*,0),
--     "CHILD"	NUMBER NULL,
--     CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
--     CONSTRAINT "PARENT_CHILD_FK" FOREIGN KEY ("CHILD") REFERENCES CI_ADMIN_B.CHILD ("ID") DEFERRABLE INITIALLY IMMEDIATE
--  );
--CREATE SEQUENCE CI_ADMIN_B.PARENT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
