INSERT INTO "DATA_CHANGE_EVENT" (ID, CHANGE_TIME, VERSION) VALUES ('1', '123456789', '1');

INSERT INTO "DATA_CHANGE_ENTRY" (ID, ENTITY_TYPE, ID_INDEX, OBJECT_ID, OBJECT_VERSION, UPDATE_PARENT, VERSION) VALUES ('11', '21', '-1', '2', '21', '1', '1');

INSERT INTO "ENTITY_TYPE" (ID, TYPE, VERSION) VALUES ('21', 'de.osthus.ambeth.model.DataChangeEntryBO', '1');
