CREATE TABLE "ENTITY_A"
  (
    "ID"			NUMBER(9,0) NOT NULL,
    "OTHER"			NUMBER(9,0) NOT NULL,
    "ENTITY_D"		NUMBER(9,0) NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 BYTE),
    "CREATED_BY"	VARCHAR2(16 BYTE),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "ENTITY_A_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "LINK_ENTITY_A_OTHER_FK1" FOREIGN KEY ("OTHER") REFERENCES "ENTITY_B" ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ENTITY_A_ENTITY_D_FK1" FOREIGN KEY ("ENTITY_D") REFERENCES "ENTITY_D" ("ID") DEFERRABLE INITIALLY DEFERRED
  );
CREATE SEQUENCE "ENTITY_A_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ENTITY_B"
  (
    "ID"			NUMBER(9,0) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 BYTE),
    "CREATED_BY"	VARCHAR2(16 BYTE),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "ENTITY_B_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ENTITY_B_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ENTITY_C"
  (
    "ID"			NUMBER(9,0) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 BYTE),
    "CREATED_BY"	VARCHAR2(16 BYTE),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "ENTITY_C_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ENTITY_C_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ENTITY_D"
  (
    "ID"			NUMBER(9,0) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 BYTE),
    "CREATED_BY"	VARCHAR2(16 BYTE),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "ENTITY_D_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ENTITY_D_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "LINK_ENTITY_A_ENTITY_C"
  (
    "A_ID"	NUMBER(9,0) NOT NULL,
    "C_ID"	NUMBER(9,0) NOT NULL,
    CONSTRAINT "LINK_ENTITY_A_ENTITY_C_PK" PRIMARY KEY ("A_ID", "C_ID") USING INDEX,
    CONSTRAINT "LINK_ENTITY_A_ENTITY_C_FK1" FOREIGN KEY ("A_ID") REFERENCES "ENTITY_A" ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ENTITY_A_ENTITY_C_FK2" FOREIGN KEY ("C_ID") REFERENCES "ENTITY_C" ("ID") DEFERRABLE INITIALLY DEFERRED
  );
