CREATE TABLE ${database.schema.name.0}.CHILD
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
  );
--CREATE SEQUENCE ${database.schema.name.0}.CHILD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE ${database.schema.name.0}.PARENT
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    "CHILD"		NUMBER NULL,
    CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "PARENT_CHILD_FK" FOREIGN KEY ("CHILD") REFERENCES ${database.schema.name.0}.CHILD ("ID") DEFERRABLE INITIALLY IMMEDIATE
 );
--CREATE SEQUENCE ${database.schema.name.0}.PARENT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE ${database.schema.name.1}.CHILD
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
  );
--CREATE SEQUENCE ${database.schema.name.1}.CHILD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE ${database.schema.name.1}.PARENT
  (
    "ID"		NUMBER NOT NULL,
    "VERSION"	NUMBER(*,0),
    "CHILD"	NUMBER NULL,
    CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "PARENT_CHILD_FK" FOREIGN KEY ("CHILD") REFERENCES ${database.schema.name.1}.CHILD ("ID") DEFERRABLE INITIALLY IMMEDIATE
  );
--CREATE SEQUENCE ${database.schema.name.1}.PARENT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
