--CREATE TABLE "BLOB_RELATED_ENTITY"
--  (
    --"ID"   VARCHAR2(20 BYTE) NOT NULL,
    --"NAME" VARCHAR2(20 BYTE) NOT NULL,
    --"UPDATED_ON" DATE,
    --"CREATED_ON" DATE,
    --"UPDATED_BY" VARCHAR2(16 BYTE),
    --"CREATED_BY" VARCHAR2(16 BYTE),
    --"VERSION"    NUMBER(*,0),
    --CONSTRAINT "BLOB_RELATED_ENTITY_PK" PRIMARY KEY ("ID") USING INDEX
  --);
--CREATE SEQUENCE "BLOB_RELATED_ENTITY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
  
CREATE TABLE "BLOB_OBJECT"
  (
    "ID"   NUMBER NOT NULL,
    "CONTENT" BLOB,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "BLOB_OBJECT_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "BLOB_OBJECT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

--CREATE TABLE "LINK_RELATED_ENTITY_TO_BLOB_OBJECT"
--  (
    --"RELATED_ENTITY_ID"  NUMBER NOT NULL,
    --"BLOB_OBJECT_ID" NUMBER NOT NULL,
    --CONSTRAINT "LINK_RELATED_ENTITY_TO_BLOB_OBJECT_PK" PRIMARY KEY ("RELATED_ENTITY_ID", "BLOB_OBJECT_ID") USING INDEX,
    --CONSTRAINT "LINK_RELATED_ENTITY_TO_BLOB_OBJECT_FK1" FOREIGN KEY ("RELATED_ENTITY_ID") REFERENCES "BLOB_RELATED_ENTITY" ("ID") DEFERRABLE INITIALLY IMMEDIATE,
    --CONSTRAINT "LINK_RELATED_ENTITY_TO_BLOB_OBJECT_FK2" FOREIGN KEY ("BLOB_OBJECT_ID") REFERENCES "BLOB_OBJECT" ("ID") DEFERRABLE INITIALLY IMMEDIATE
  --);