CREATE TABLE "CLOB_OBJECT"
  (
    "ID"   NUMBER NOT NULL,
    "CONTENT" CLOB,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "CLOB_OBJECT_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "CLOB_OBJECT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;