CREATE TABLE "TEST_ENTITY2" (
	"ID"			NUMBER(11,0) NOT NULL,
	"UPDATED_ON"	TIMESTAMP,
	"CREATED_ON"	TIMESTAMP NOT NULL,
	"UPDATED_BY"	VARCHAR2(16 CHAR),
	"CREATED_BY"	VARCHAR2(16 CHAR) NOT NULL,
	"VERSION"		NUMBER(11,0) NOT NULL,
	"MY_VALUE2"		NUMBER(11,0),
	CONSTRAINT "PK_TEST_ENTITY2" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "TEST_ENTITY2_SEQ"  MINVALUE 1 MAXVALUE 2000000000 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "TEST_ENTITY" (
	"ID"			NUMBER(11,0) NOT NULL,
	"UPDATED_ON"	TIMESTAMP,
	"CREATED_ON"	TIMESTAMP NOT NULL,
	"UPDATED_BY"	VARCHAR2(16 CHAR),
	"CREATED_BY"	VARCHAR2(16 CHAR) NOT NULL,
	"VERSION"		NUMBER(11,0) NOT NULL,
	"RELATION"		NUMBER(11,0),
	"EMB_RELATION"	NUMBER(11,0),
	"NAME"			VARCHAR2(64 CHAR),
	"VALUE"			NUMBER(11,0),
	"MY_VALUE"		NUMBER(11,0),
	CONSTRAINT "PK_TEST_ENTITY" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "LINK_TEST_TEST2_FK1" FOREIGN KEY ("RELATION") REFERENCES "TEST_ENTITY2" ("ID") DEFERRABLE INITIALLY DEFERRED, 
	CONSTRAINT "LINK_TEST_EMB_TEST2_FK1" FOREIGN KEY ("EMB_RELATION") REFERENCES "TEST_ENTITY2" ("ID") DEFERRABLE INITIALLY DEFERRED 
);
CREATE SEQUENCE "TEST_ENTITY_SEQ"  MINVALUE 1 MAXVALUE 2000000000 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "TEST_ENTITY3" (
	"ID"			NUMBER(11,0) NOT NULL,
	"UPDATED_ON"	TIMESTAMP,
	"CREATED_ON"	TIMESTAMP NOT NULL,
	"UPDATED_BY"	VARCHAR2(16 CHAR),
	"CREATED_BY"	VARCHAR2(16 CHAR) NOT NULL,
	"VERSION"		NUMBER(11,0) NOT NULL,
	"MY_VALUE3"		VARCHAR2(4000 CHAR),
	"TEST_ID"		NUMBER(11,0) NOT NULL,
    CONSTRAINT "PK_TEST_ENTITY3" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "LINK_TEST3_TEST_FK1" FOREIGN KEY ("TEST_ID") REFERENCES "TEST_ENTITY" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "TEST_ENTITY3_SEQ"  MINVALUE 1 MAXVALUE 2000000000 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;
