INSERT INTO COMPOSITE_ID_ENTITY (ID1, ID2, NAME) VALUES ('1', 'eins', 'name_eins1');
INSERT INTO COMPOSITE_ID_ENTITY (ID1, ID2, NAME) VALUES ('1', 'einszwo', 'name_einszwo1');
INSERT INTO COMPOSITE_ID_ENTITY (ID1, ID2, NAME) VALUES ('2', 'zwei', 'name_zwei2');
INSERT INTO COMPOSITE_ID_ENTITY (ID1, ID2, NAME) VALUES ('2', 'eins', 'name_eins2');
