CREATE TABLE "PARENT"
(
    "ID"			NUMBER(9,0) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 CHAR),
    "CREATED_BY"	VARCHAR2(16 CHAR),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "PK_PARENT" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "PARENT_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "CHILD"
(
    "ID"			NUMBER(9,0) NOT NULL,
    "PARENT"		NUMBER(9,0) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 CHAR),
    "CREATED_BY"	VARCHAR2(16 CHAR),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "LINK_CHILD_PARENT_FK1" FOREIGN KEY ("PARENT") REFERENCES "PARENT" ("ID") DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT "PK_CHILD" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "CHILD_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;
