INSERT INTO "MULTI_EVENT_ENTITY" ("ID", "NAME", "VERSION") VALUES ('1', 'Name 1.1', '1');
INSERT INTO "MULTI_EVENT_ENTITY" ("ID", "NAME", "VERSION") VALUES ('2', 'Name 2.1', '1');
INSERT INTO "MULTI_EVENT_ENTITY" ("ID", "NAME", "VERSION") VALUES ('3', 'Name 3.1', '1');

INSERT INTO "MULTI_EVENT_ENTITY2" ("ID", "NAME", "VERSION") VALUES ('1', 'Name2 1.1', '1');
