INSERT INTO "ENTITY_A" (ID, NAME, VERSION) VALUES ('1', 'ENTITY_A 1', '1');

INSERT INTO "ENTITY_B" (ID, NAME, ENTITY_A_ID, VERSION) VALUES ('11', 'ENTITY_B 11', '1', '1');
INSERT INTO "ENTITY_B" (ID, NAME, VERSION) VALUES ('12', 'ENTITY_B 12', '1');
INSERT INTO "ENTITY_B" (ID, NAME, VERSION) VALUES ('13', 'ENTITY_B 13', '1');
