CREATE TABLE "GROUP"
  (
    "ID"   NUMBER(18,0) NOT NULL,
    "VERSION"    NUMBER(18,0) NOT NULL,
    "Name" VARCHAR2(50 BYTE) NOT NULL,
    CONSTRAINT "GROUP_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "GROUP_AE_NAME" UNIQUE ("Name")
  );
CREATE SEQUENCE "GROUP_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "LINK_GROUP_GROUP"
  (
    "GROUP_ID"  NUMBER(18,0) NOT NULL,
    "CHILD_GROUP_ID" NUMBER(18,0) NOT NULL,
    CONSTRAINT "LINK_GROUP_PROJECT_PK" PRIMARY KEY ("GROUP_ID", "CHILD_GROUP_ID") USING INDEX,
    CONSTRAINT "LINK_GROUP_PROJECT_FK1" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_GROUP_PROJECT_FK2" FOREIGN KEY ("CHILD_GROUP_ID") REFERENCES "GROUP" ("ID") DEFERRABLE INITIALLY DEFERRED
  );
