
CREATE TABLE "PARENT"
(
	"ID"		NUMBER(18,0) NOT NULL,
	"NAME"		VARCHAR2(50 BYTE) NOT NULL,
	"CHILD"		NUMBER(18,0),
	"VERSION"	NUMBER(18,0) NOT NULL,
	CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID") USING INDEX,
	CONSTRAINT "PARENT_CHILD_FK1" FOREIGN KEY ("CHILD") REFERENCES "CHILD" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "PARENT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "CHILD"
(
	"ID"		NUMBER(18,0) NOT NULL,
	"NAME"		VARCHAR2(50 BYTE) NOT NULL,
	"PARENT"	NUMBER(18,0),
	"PARENT2"	NUMBER(18,0),
	"VERSION"	NUMBER(18,0) NOT NULL,
	CONSTRAINT "CHILD_PK" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "CHILD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

ALTER TABLE "CHILD" ADD	CONSTRAINT "CHILD_PARENT_FK2" FOREIGN KEY ("PARENT") REFERENCES "PARENT" ("ID") DEFERRABLE INITIALLY DEFERRED ;
ALTER TABLE "CHILD" ADD	CONSTRAINT "CHILD_PARENT_FK3" FOREIGN KEY ("PARENT2") REFERENCES "PARENT" ("ID") DEFERRABLE INITIALLY DEFERRED ;

