INSERT INTO "MULTI_ALTERNATE_ID_ENTITY" (ID, ALTERNATE_ID1, ALTERNATE_ID2, VERSION) 
VALUES ('1', 'AID1.1', 'AID1.2', '2');

INSERT INTO "MULTI_ALTERNATE_ID_ENTITY" (ID, ALTERNATE_ID1, ALTERNATE_ID2, VERSION) 
VALUES ('2', 'AID2.1', 'AID2.2', '1');

INSERT INTO "MULTI_ALTERNATE_ID_ENTITY" (ID, ALTERNATE_ID1, ALTERNATE_ID2, VERSION) 
VALUES ('3', 'AID3.1', 'AID3.2', '2');
