CREATE OR REPLACE TYPE "CHAR_ARRAY" AS VARRAY(4000) OF CHAR(50);
CREATE OR REPLACE TYPE "STRING_ARRAY" AS VARRAY(4000) OF VARCHAR2(4000 CHAR);

CREATE TABLE "MATERIAL"
  (
    "ID"   NUMBER NOT NULL,
    "VERSION"    NUMBER(*,0),
    "NAME" VARCHAR2(20 BYTE),
    "BUID" VARCHAR2(20 BYTE),
    "UNIT" VARCHAR2(20 BYTE),
    "MATERIAL_GROUP" VARCHAR2(20 BYTE),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    CONSTRAINT "MATERIAL_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "MATERIAL_NAME" UNIQUE ("NAME"),
    CONSTRAINT "MATERIAL_BUID" UNIQUE ("BUID"),
    CONSTRAINT "MATERIAL_UNIT_FK" FOREIGN KEY ("UNIT") REFERENCES "UNIT" ("BUID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "MATERIAL_MATERIAL_GROUP_FK" FOREIGN KEY ("MATERIAL_GROUP") REFERENCES MATERIAL_GROUP ("BUID") DEFERRABLE INITIALLY DEFERRED
  );
CREATE SEQUENCE "MATERIAL_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "MATERIAL_GROUP"
  (
    "ID"   NUMBER NOT NULL,
    "VERSION"    NUMBER(*,0),
    "NAME" VARCHAR2(20 BYTE),
    "BUID" VARCHAR2(20 BYTE),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    CONSTRAINT "MATERIAL_GROUP_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "MATERIAL_GROUP_BUID" UNIQUE ("BUID")
  );
CREATE SEQUENCE "MATERIAL_GROUP_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "UNIT"
  (
    "ID"   NUMBER NOT NULL,
    "VERSION"    NUMBER(*,0),
    "NAME" VARCHAR2(20 BYTE),
    "BUID" VARCHAR2(20 BYTE),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    CONSTRAINT "UNIT_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "UNIT_BUID" UNIQUE ("BUID")
  );
CREATE SEQUENCE "UNIT_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "SELF_REFERENCING_ENTITY"
  (
    "ID" NUMBER NOT NULL,
    "VERSION"    NUMBER(*,0),
    "NAME" VARCHAR2(20 BYTE),
    "VALUES" CHAR_ARRAY,
    "VALUES2" CHAR_ARRAY,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    "RELATION1" VARCHAR2(20 BYTE),
    "RELATION2" VARCHAR2(20 BYTE),
    CONSTRAINT "SELF_REFERENCING_ENTITY_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "SELF_REFERENCING_ENTITY_NAME" UNIQUE ("NAME"),
    CONSTRAINT "LINK_SELF_REF_R1_SELF_REF_NAME" FOREIGN KEY ("RELATION1") REFERENCES SELF_REFERENCING_ENTITY ("NAME") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_SELF_REF_R2_SELF_REF_NAME" FOREIGN KEY ("RELATION2") REFERENCES SELF_REFERENCING_ENTITY ("NAME") DEFERRABLE INITIALLY DEFERRED
  );
CREATE SEQUENCE "SELF_REFERENCING_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "ONE_TO_MANY_ENTITY"
  (
    "ID" NUMBER NOT NULL,
    "VERSION"    NUMBER(*,0),
    "NAME" VARCHAR2(20 BYTE),
    "NICKNAMES" STRING_ARRAY,
    "EMB_NAME" VARCHAR2(20 BYTE),
    "EMB_VALUE" NUMBER,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 BYTE),
    "CREATED_BY" VARCHAR2(16 BYTE),
    CONSTRAINT "ONE_TO_MANY_ENTITY_PK" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "ONE_TO_MANY_ENTITY_NAME" UNIQUE ("NAME")
  );
CREATE SEQUENCE "ONE_TO_MANY_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "LINK_ONE_TO_MANY_ENTITY_1"
  (
    "LEFT_ID" NUMBER,
    "RIGHT_ID" NUMBER,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_1_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_1_FROM" FOREIGN KEY ("LEFT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_1_TO" FOREIGN KEY ("RIGHT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED
  );

CREATE TABLE "LINK_ONE_TO_MANY_ENTITY_2"
  (
    "LEFT_ID" NUMBER,
    "RIGHT_ID" NUMBER,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_2_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_2_FROM" FOREIGN KEY ("LEFT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_2_TO" FOREIGN KEY ("RIGHT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED
  );
 
CREATE TABLE "LINK_ONE_TO_MANY_ENTITY_3"
  (
    "LEFT_ID" NUMBER,
    "RIGHT_ID" NUMBER,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_3_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_3_FROM" FOREIGN KEY ("LEFT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_3_TO" FOREIGN KEY ("RIGHT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED
  );
   
CREATE TABLE "LINK_ONE_TO_MANY_ENTITY_4"
  (
    "LEFT_ID" NUMBER,
    "RIGHT_ID" NUMBER,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_4_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_4_FROM" FOREIGN KEY ("LEFT_ID") REFERENCES ONE_TO_MANY_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_ONE_TO_MANY_ENTITY_4_TO" FOREIGN KEY ("RIGHT_ID") REFERENCES SELF_REFERENCING_ENTITY ("ID") DEFERRABLE INITIALLY DEFERRED
  );
