CREATE TABLE "ITEST_ENTITY"
  (
    "ID"   NUMBER(9,0) NOT NULL,
    "NAME" VARCHAR2(50 CHAR) NOT NULL,
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE NOT NULL,
    "UPDATED_BY" VARCHAR2(16 CHAR),
    "CREATED_BY" VARCHAR2(16 CHAR) NOT NULL,
    "VERSION"    NUMBER(4,0) NOT NULL,
    CONSTRAINT "ITEST_ENTITY_PK" PRIMARY KEY ("ID") USING INDEX
  );
CREATE SEQUENCE "ITEST_ENTITY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER NOCYCLE ;
