CREATE TABLE "TBL_NO_PK"
  (
    "NO_PK_ID"   NUMBER NOT NULL
);
CREATE SEQUENCE "TBL_NO_PK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "TBL_NO_SEQ"
  (
    "NO_SEQ_ID"   NUMBER NOT NULL,
    CONSTRAINT "PK_NO_SEQ" PRIMARY KEY ("NO_SEQ_ID") USING INDEX
);

CREATE TABLE "TBL_MAY_BE_LINK"
  (
    "NO_LINK_LEFT_ID"   NUMBER NOT NULL,
    "NO_LINK_RIGHT_ID"   NUMBER NOT NULL,
    CONSTRAINT "PK_MAY_BE_LINK" PRIMARY KEY ("NO_LINK_LEFT_ID", "NO_LINK_RIGHT_ID") USING INDEX
);
CREATE SEQUENCE "TBL_MAY_BE_LINK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE ;

CREATE TABLE "TBL_RIGHT"
  (
    "RIGHT_ID"   NUMBER NOT NULL,
    CONSTRAINT "PK_RIGHT" PRIMARY KEY ("RIGHT_ID") USING INDEX
);

CREATE TABLE "TBL_LEFT"
  (
    "LEFT_ID"   NUMBER NOT NULL,
    "FK_RIGHT_ID"   NUMBER NOT NULL,
    CONSTRAINT "TBL_LEFT_FK_RIGHT_ID" FOREIGN KEY ("FK_RIGHT_ID") REFERENCES "TBL_RIGHT" ("RIGHT_ID") DEFERRABLE INITIALLY IMMEDIATE
);