package de.osthus.ambeth.security;

public interface ISecurityScopeChangeListenerExtendable
{
	void registerSecurityScopeChangeListener(ISecurityScopeChangeListener securityScopeChangeListener);
	
	void unregisterSecurityScopeChangeListener(ISecurityScopeChangeListener securityScopeChangeListener);
}