INSERT INTO "ENTITY_A" ("ID", "BUID", "ENTITY_B", "VERSION") VALUES ('1', 'BUID 1', '11', '1');
INSERT INTO "ENTITY_A" ("ID", "BUID", "ENTITY_B", "VERSION") VALUES ('2', 'BUID 2', '13', '1');
INSERT INTO "ENTITY_A" ("ID", "BUID", "ENTITY_B", "VERSION") VALUES ('3', 'BUID 3', '12', '5');
INSERT INTO "ENTITY_A" ("ID", "BUID", "ENTITY_B", "VERSION") VALUES ('4', 'BUID 4', '12', '1');

INSERT INTO "ENTITY_B" ("ID", "BUID", "VERSION") VALUES ('11', 'BUID 11', '2');
INSERT INTO "ENTITY_B" ("ID", "BUID", "VERSION") VALUES ('12', 'BUID 12', '5');
INSERT INTO "ENTITY_B" ("ID", "BUID", "VERSION") VALUES ('13', 'BUID 13', '2');
