CREATE TABLE "MULTI_ALTERNATE_ID_ENTITY"
  (
    "ID"			NUMBER(9,0) NOT NULL,
    "ALTERNATE_ID1"	VARCHAR2(20 CHAR) NOT NULL,
    "ALTERNATE_ID2"	VARCHAR2(20 CHAR) NOT NULL,
    "UPDATED_ON"	DATE,
    "CREATED_ON"	DATE,
    "UPDATED_BY"	VARCHAR2(16 CHAR),
    "CREATED_BY"	VARCHAR2(16 CHAR),
    "VERSION"		NUMBER(9,0),
    CONSTRAINT "PK_MAID_ENTITY" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "UK_MAID_ENTITY_NAME1" UNIQUE ("ALTERNATE_ID1"),
    CONSTRAINT "UK_MAID_ENTITY_NAME2" UNIQUE ("ALTERNATE_ID2")
);
CREATE SEQUENCE "MULTI_ALTERNATE_ID_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;
