---
-- #%L
-- jambeth-test
-- %%
-- Copyright (C) 2017 Koch Softwaredevelopment
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-- #L%
---
CREATE TABLE EntityA
  (
    Id		NUMBER(9,0) NOT NULL,
    Version	NUMBER(9,0) NOT NULL,
    CONSTRAINT PK_EntityA PRIMARY KEY (Id) USING INDEX
);
CREATE SEQUENCE EntityA_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE EntityB
  (
    Id		NUMBER(9,0) NOT NULL,
    Version	NUMBER(9,0) NOT NULL,
    CONSTRAINT PK_EntityB PRIMARY KEY (Id) USING INDEX
);
CREATE SEQUENCE EntityB_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE EntityC
  (
    Id		NUMBER(9,0) NOT NULL,
    Version	NUMBER(9,0) NOT NULL,
    CONSTRAINT PK_EntityC PRIMARY KEY (Id) USING INDEX
);
CREATE SEQUENCE EntityC_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE EntityD
  (
    Id		NUMBER(9,0) NOT NULL,
    Version	NUMBER(9,0) NOT NULL,
    CONSTRAINT PK_EntityD PRIMARY KEY (Id) USING INDEX
);
CREATE SEQUENCE EntityD_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE L_EntityA_EntityAs
  (
    Left_Id NUMBER(9,0) NOT NULL,
    Right_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityA_EntityAs_PK PRIMARY KEY (Left_Id, Right_Id) USING INDEX,
    CONSTRAINT L_EntityA_EntityAs_FK1 FOREIGN KEY (Left_Id) REFERENCES EntityA (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityA_EntityAs_FK2 FOREIGN KEY (Right_Id) REFERENCES EntityA (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityA_EntityAs_FK2_IDX ON L_EntityA_EntityAs (Right_Id);

CREATE TABLE L_EntityA_EntityBs
  (
    EntityA_Id NUMBER(9,0) NOT NULL,
    EntityB_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityA_EntityBs_PK PRIMARY KEY (EntityA_Id, EntityB_Id) USING INDEX,
    CONSTRAINT L_EntityA_EntityBs_FK1 FOREIGN KEY (EntityA_Id) REFERENCES EntityA (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityA_EntityBs_FK2 FOREIGN KEY (EntityB_Id) REFERENCES EntityB (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityA_EntityBs_FK2_IDX ON L_EntityA_EntityBs (EntityB_Id);

CREATE TABLE L_EntityA_EntityCs
  (
    EntityA_Id NUMBER(9,0) NOT NULL,
    EntityC_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityA_EntityCs_PK PRIMARY KEY (EntityA_Id, EntityC_Id) USING INDEX,
    CONSTRAINT L_EntityA_EntityCs_FK1 FOREIGN KEY (EntityA_Id) REFERENCES EntityA (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityA_EntityCs_FK2 FOREIGN KEY (EntityC_Id) REFERENCES EntityC (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityA_EntityCs_FK2_IDX ON L_EntityA_EntityCs (EntityC_Id);

CREATE TABLE L_EntityB_EntityAs
  (
    EntityB_Id NUMBER(9,0) NOT NULL,
    EntityA_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityB_EntityAs_PK PRIMARY KEY (EntityB_Id, EntityA_Id) USING INDEX,
    CONSTRAINT L_EntityB_EntityAs_FK1 FOREIGN KEY (EntityB_Id) REFERENCES EntityB (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityB_EntityAs_FK2 FOREIGN KEY (EntityA_Id) REFERENCES EntityA (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityB_EntityAs_FK2_IDX ON L_EntityB_EntityAs (EntityA_Id);

CREATE TABLE L_EntityB_EntityBs
  (
    Left_Id NUMBER(9,0) NOT NULL,
    Right_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityB_EntityBs_PK PRIMARY KEY (Left_Id, Right_Id) USING INDEX,
    CONSTRAINT L_EntityB_EntityBs_FK1 FOREIGN KEY (Left_Id) REFERENCES EntityB (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityB_EntityBs_FK2 FOREIGN KEY (Right_Id) REFERENCES EntityB (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityB_EntityBs_FK2_IDX ON L_EntityB_EntityBs (Right_Id);

CREATE TABLE L_EntityB_EntityCs
  (
    EntityB_Id NUMBER(9,0) NOT NULL,
    EntityC_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityB_EntityCs_PK PRIMARY KEY (EntityB_Id, EntityC_Id) USING INDEX,
    CONSTRAINT L_EntityB_EntityCs_FK1 FOREIGN KEY (EntityB_Id) REFERENCES EntityB (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityB_EntityCs_FK2 FOREIGN KEY (EntityC_Id) REFERENCES EntityC (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityB_EntityCs_FK2_IDX ON L_EntityB_EntityCs (EntityC_Id);

CREATE TABLE L_EntityC_EntityCs
  (
    Left_Id NUMBER(9,0) NOT NULL,
    Right_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityC_EntityCs_PK PRIMARY KEY (Left_Id, Right_Id) USING INDEX,
    CONSTRAINT L_EntityC_EntityCs_FK1 FOREIGN KEY (Left_Id) REFERENCES EntityC (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityC_EntityCs_FK2 FOREIGN KEY (Right_Id) REFERENCES EntityC (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityC_EntityCs_FK2_IDX ON L_EntityC_EntityCs (Right_Id);

CREATE TABLE L_EntityD_EntityDs
  (
    Left_Id NUMBER(9,0) NOT NULL,
    Right_Id NUMBER(9,0) NOT NULL,
    CONSTRAINT L_EntityD_EntityDs_PK PRIMARY KEY (Left_Id, Right_Id) USING INDEX,
    CONSTRAINT L_EntityD_EntityDs_FK1 FOREIGN KEY (Left_Id) REFERENCES EntityD (Id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT L_EntityD_EntityDs_FK2 FOREIGN KEY (Right_Id) REFERENCES EntityD (Id) DEFERRABLE INITIALLY DEFERRED
  );
CREATE INDEX L_EntityD_EntityDs_FK2_IDX ON L_EntityD_EntityDs (Right_Id);
