CREATE TABLE "QUERY_ENTITY"
  (
    "ID"   NUMBER NOT NULL,
    "FK"   NUMBER NULL,
    "NAME1" VARCHAR2(20 CHAR) NOT NULL,
    "NAME2" VARCHAR2(20 CHAR),
    "FTNAME1" VARCHAR2(500 CHAR),
    "FTNAME2" VARCHAR2(500 CHAR),
    "CONTENT"	 FLOAT(6),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 CHAR),
    "CREATED_BY" VARCHAR2(16 CHAR),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "PK_QUERY_ENTITY" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "UK_QUERY_ENTITY_NAME" UNIQUE ("NAME1"),
    CONSTRAINT "LINK_QE_JQE_FK1" FOREIGN KEY ("FK") REFERENCES "JOIN_QUERY_ENTITY" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "QUERY_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "JOIN_QUERY_ENTITY"
  (
    "ID"   NUMBER NOT NULL,
    "PARENT"	 NUMBER,
    "CONTENT"	 FLOAT(6),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 CHAR),
    "CREATED_BY" VARCHAR2(16 CHAR),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "PK_JOIN_QUERY_ENTITY" PRIMARY KEY ("ID") USING INDEX,
    CONSTRAINT "LINK_JQE_JQE_FK1" FOREIGN KEY ("PARENT") REFERENCES "JOIN_QUERY_ENTITY" ("ID") DEFERRABLE INITIALLY DEFERRED
);
CREATE SEQUENCE "JOIN_QUERY_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "LINK_TABLE_ENTITY"
  (
    "ID"   NUMBER NOT NULL,
    "NAME" VARCHAR2(20 BYTE),
    "UPDATED_ON" DATE,
    "CREATED_ON" DATE,
    "UPDATED_BY" VARCHAR2(16 CHAR),
    "CREATED_BY" VARCHAR2(16 CHAR),
    "VERSION"    NUMBER(*,0),
    CONSTRAINT "PK_LINK_TABLE_ENTITY" PRIMARY KEY ("ID") USING INDEX
);
CREATE SEQUENCE "QUERY_ENTITY_SEQ" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE "LINK_QE_LTE"
  (
    "LEFT_ID"  NUMBER NOT NULL,
    "RIGHT_ID" NUMBER NOT NULL,
    CONSTRAINT "LINK_QE_LTE_PK" PRIMARY KEY ("LEFT_ID", "RIGHT_ID") USING INDEX,
    CONSTRAINT "LINK_QE_LTE_FK1" FOREIGN KEY ("LEFT_ID") REFERENCES "QUERY_ENTITY" ("ID") DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "LINK_QE_LTE_FK2" FOREIGN KEY ("RIGHT_ID") REFERENCES "LINK_TABLE_ENTITY" ("ID") DEFERRABLE INITIALLY DEFERRED
  );
